use jankurai::audit::{run_audit_with_options, AuditOptions};
use jankurai::model::{DimensionResult, Report};
use std::fs;
use std::path::Path;
use std::process::Command;
use tempfile::tempdir;

fn run_changed_fast(repo: &Path, changed: &str) -> Report {
    run_audit_with_options(
        repo,
        &[repo.join(changed)],
        AuditOptions {
            self_audit: false,
            proof_receipts: None,
            changed_fast: true,
        },
    )
    .unwrap()
}

fn dimension<'a>(report: &'a Report, name: &str) -> &'a DimensionResult {
    report
        .dimensions
        .iter()
        .find(|dim| dim.name == name)
        .unwrap_or_else(|| panic!("missing dimension {name}"))
}

fn assert_unrelated_source_excluded(report: &Report) {
    assert!(!report
        .findings
        .iter()
        .any(|finding| finding.path == "src/unrelated.rs"));
}

fn write_generic_support_fixture(repo: &Path) {
    fs::write(repo.join("AGENTS.md"), "Read agent standard\n").unwrap();
    fs::write(
        repo.join("README.md"),
        "# Repo\n\nRust workspace layout and validation map.\n",
    )
    .unwrap();
    fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"1.0.0\"\n",
    )
    .unwrap();
    fs::write(repo.join("Cargo.lock"), "version = 4\n").unwrap();

    fs::create_dir_all(repo.join("agent")).unwrap();
    fs::write(
        repo.join("agent/audit-policy.toml"),
        "[policy]\nminimum_score = 85\n",
    )
    .unwrap();
    fs::write(
        repo.join("agent/generated-zones.toml"),
        "[[zone]]\npath = \"target/generated/event.rs\"\nsource = \"contracts/generated/event.schema.json\"\ncommand = \"generate contracts\"\nread_only = false\nwrite_policy = \"generator_only\"\n",
    )
    .unwrap();
    fs::write(
        repo.join("agent/boundaries.toml"),
        "schema_version = \"jankurai.boundaries/v1\"\n",
    )
    .unwrap();

    fs::write(
        repo.join("Justfile"),
        "check:\n    cargo test\nfast:\n    cargo check\n",
    )
    .unwrap();
    fs::create_dir_all(repo.join(".github/workflows")).unwrap();
    fs::write(
        repo.join(".github/workflows/jankurai.yml"),
        "jobs:\n  audit:\n    steps:\n      - run: jankurai audit . --json target/repo-score.json\n",
    )
    .unwrap();
    fs::create_dir_all(repo.join("ops/ci")).unwrap();
    fs::write(
        repo.join("ops/ci/split-host-ci-parent.sh"),
        "#!/bin/sh\nset -eu\ncargo check\n",
    )
    .unwrap();

    fs::create_dir_all(repo.join("tools")).unwrap();
    fs::write(
        repo.join("tools/security-lane.sh"),
        "#!/bin/sh\nset -eu\ncargo audit\nnpm audit\ngitleaks detect\nsyft .\nactionlint\nzizmor .github/workflows\n",
    )
    .unwrap();

    fs::create_dir_all(repo.join("contracts/generated")).unwrap();
    fs::write(
        repo.join("contracts/generated/event.schema.json"),
        "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"description\":\"Generated by: contract renderer\"}\n",
    )
    .unwrap();
    fs::create_dir_all(repo.join("schemas")).unwrap();
    fs::write(
        repo.join("schemas/repo-score.schema.json"),
        "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\"}\n",
    )
    .unwrap();
    fs::write(
        repo.join("schemas/repair-queue.schema.json"),
        "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\"}\n",
    )
    .unwrap();

    fs::create_dir_all(repo.join("db/migrations")).unwrap();
    fs::create_dir_all(repo.join("db/constraints")).unwrap();
    fs::write(
        repo.join("db/README.md"),
        "# Data policy\n\nForeign key and check constraint rules require row level security, rollback, backfill, and lock review.\n",
    )
    .unwrap();
    fs::write(
        repo.join("db/migrations/README.md"),
        "# Migrations\n\nRollback and backfill receipts are mandatory.\n",
    )
    .unwrap();
    fs::write(
        repo.join("db/constraints/README.md"),
        "# Constraints\n\nForeign key and check constraint ownership is explicit.\n",
    )
    .unwrap();

    fs::create_dir_all(repo.join("src")).unwrap();
    fs::write(
        repo.join("src/unrelated.rs"),
        "fn unrelated() { todo!(\"must remain outside changed-fast\"); }\n",
    )
    .unwrap();
}

#[test]
fn changed_fast_scope_is_advisory_and_partial() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("AGENTS.md"), "Read agent standard\n").unwrap();
    fs::write(dir.path().join("Justfile"), "check:\n    cargo test\n").unwrap();
    fs::write(dir.path().join("README.md"), "# Repo\n").unwrap();
    fs::create_dir_all(dir.path().join("src")).unwrap();
    fs::write(
        dir.path().join("src/unrelated.rs"),
        "fn unrelated() { todo!(\"not in changed-fast scope\"); }\n",
    )
    .unwrap();

    let report = run_changed_fast(dir.path(), "README.md");

    assert_eq!(report.scope.mode, "changed-fast");
    assert_eq!(report.scope.paths, vec!["README.md".to_string()]);
    assert_unrelated_source_excluded(&report);
}

#[test]
fn changed_fast_inventories_unchanged_readme_and_release_evidence() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("AGENTS.md"), "Read agent standard\n").unwrap();
    fs::write(
        dir.path().join("README.md"),
        "# Repo\n\n[![CI](https://img.shields.io/badge/ci-green.svg)](ci)\n\nBuilt on a Rust core. See [AGENTS.md](AGENTS.md).\n\n## Quick start\n\n```sh\ncargo test\n```\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"1.0.0\"\n",
    )
    .unwrap();
    fs::write(dir.path().join("CHANGELOG.md"), "# Changelog\n").unwrap();
    fs::write(
        dir.path().join("Justfile"),
        "check:\n    cargo test\nrelease:\n    cargo test\n",
    )
    .unwrap();
    fs::create_dir_all(dir.path().join("docs")).unwrap();
    fs::write(
        dir.path().join("docs/architecture.md"),
        "# Architecture\n\nRust workspace boundaries.\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("docs/testing.md"),
        "# Testing\n\nRun cargo test.\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("docs/release.md"),
        "# Release process\n\nThe release gate requires security review, backup rehearsal, monitoring, rollback, and rate limit abuse controls. Verify SHA256 checksums, provenance, and the SBOM before publication.\n",
    )
    .unwrap();
    fs::create_dir_all(dir.path().join("src")).unwrap();
    fs::write(
        dir.path().join("src/unrelated.rs"),
        "pub fn unrelated() -> bool { true }\n",
    )
    .unwrap();

    let report = run_changed_fast(dir.path(), "src/unrelated.rs");

    assert_eq!(report.scope.mode, "changed-fast");
    assert_eq!(report.scope.paths, vec!["src/unrelated.rs".to_string()]);
    assert!(!report
        .caps_applied
        .iter()
        .any(|cap| cap == "missing-agent-readable-docs"));
    assert!(!report
        .caps_applied
        .iter()
        .any(|cap| cap == "release-readiness-gap"));
    assert!(!report
        .findings
        .iter()
        .any(|finding| { finding.path == "README.md" || finding.path == "docs/release.md" }));
}

#[test]
fn changed_fast_inventories_unchanged_rendered_ux_evidence() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("AGENTS.md"), "Read agent standard\n").unwrap();
    fs::create_dir_all(dir.path().join("apps/web/src/storybook")).unwrap();
    fs::create_dir_all(dir.path().join("apps/web/e2e")).unwrap();
    fs::write(
        dir.path().join("apps/web/src/App.tsx"),
        "export const App = () => <main />;\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("apps/web/src/storybook/states.ts"),
        "// Component Story Format state consumed by an MSW adapter.\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("apps/web/src/styles.css"),
        "/* semantic design tokens */\n",
    )
    .unwrap();
    fs::write(
        dir.path().join("apps/web/e2e/rendered.spec.ts"),
        "// Visual review uses @axe-core/playwright, toHaveScreenshot, cumulative layout shift, and artifactPath receipts.\n",
    )
    .unwrap();

    let report = run_changed_fast(dir.path(), "apps/web/src/App.tsx");

    assert_eq!(report.scope.mode, "changed-fast");
    assert_eq!(report.scope.paths, vec!["apps/web/src/App.tsx".to_string()]);
    assert!(!report
        .caps_applied
        .iter()
        .any(|cap| cap == "missing-rendered-ux-qa-lane"));
}

#[test]
fn changed_fast_inventories_unchanged_generic_supporting_evidence() {
    let dir = tempdir().unwrap();
    write_generic_support_fixture(dir.path());

    let report = run_changed_fast(dir.path(), "ops/ci/split-host-ci-parent.sh");

    assert_eq!(report.scope.mode, "changed-fast");
    assert_eq!(
        report.scope.paths,
        vec!["ops/ci/split-host-ci-parent.sh".to_string()]
    );
    for name in [
        "Contract and boundary integrity",
        "Security and supply-chain posture",
        "Data truth and workflow safety",
        "Observability and repair evidence",
    ] {
        assert!(
            dimension(&report, name).score >= 85,
            "{name} should retain real unchanged supporting evidence: {:?}",
            dimension(&report, name)
        );
    }
    assert_unrelated_source_excluded(&report);
}

#[test]
fn changed_fast_generic_roots_are_independently_required() {
    for (root, owning_dimension) in [
        ("contracts", "Contract and boundary integrity"),
        ("schemas", "Observability and repair evidence"),
        ("db", "Data truth and workflow safety"),
        (
            "tools/security-lane.sh",
            "Security and supply-chain posture",
        ),
    ] {
        let dir = tempdir().unwrap();
        write_generic_support_fixture(dir.path());
        let baseline = run_changed_fast(dir.path(), "ops/ci/split-host-ci-parent.sh");
        let baseline_score = dimension(&baseline, owning_dimension).score;

        match root {
            "contracts" | "schemas" | "db" => {
                fs::remove_dir_all(dir.path().join(root)).unwrap();
            }
            "tools/security-lane.sh" => {
                fs::write(
                    dir.path().join(root),
                    "#!/bin/sh\nset -eu\n# intentionally missing security commands\n",
                )
                .unwrap();
            }
            _ => unreachable!(),
        }

        let degraded = run_changed_fast(dir.path(), "ops/ci/split-host-ci-parent.sh");
        let degraded_score = dimension(&degraded, owning_dimension).score;
        assert!(
            degraded_score < baseline_score,
            "removing or corrupting {root} must lower {owning_dimension}: baseline={baseline_score}, degraded={degraded_score}"
        );
        assert_unrelated_source_excluded(&degraded);
    }
}

#[test]
fn changed_fast_cli_requires_changed_scope_and_skips_score_history() {
    let dir = tempdir().unwrap();
    fs::write(dir.path().join("AGENTS.md"), "Read agent standard\n").unwrap();
    fs::write(dir.path().join("README.md"), "# Repo\n").unwrap();
    fs::write(dir.path().join("Justfile"), "check:\n    cargo test\n").unwrap();
    let json = dir.path().join("score.json");
    let md = dir.path().join("score.md");
    let history = dir.path().join("history.jsonl");

    let failed = Command::new(env!("CARGO_BIN_EXE_jankurai"))
        .arg("audit")
        .arg(dir.path())
        .arg("--changed-fast")
        .arg("--json")
        .arg(&json)
        .arg("--md")
        .arg(&md)
        .output()
        .expect("spawn changed-fast audit without scope");
    assert!(!failed.status.success());
    assert!(String::from_utf8_lossy(&failed.stderr)
        .contains("--changed-fast requires --changed PATH or --changed-from REF"));

    let output = Command::new(env!("CARGO_BIN_EXE_jankurai"))
        .arg("audit")
        .arg(dir.path())
        .arg("--changed-fast")
        .arg("--mode")
        .arg("advisory")
        .arg("--changed")
        .arg("README.md")
        .arg("--json")
        .arg(&json)
        .arg("--md")
        .arg(&md)
        .arg("--score-history")
        .arg(&history)
        .output()
        .expect("spawn changed-fast audit");
    assert!(
        output.status.success(),
        "changed-fast audit failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        !history.exists(),
        "changed-fast should not write score history"
    );
    assert!(fs::read_to_string(&md)
        .unwrap()
        .contains("changed-fast scans only changed files plus required control files"));
}
