//! Fleet-wide audit aggregation.
//!
//! The `jankurai fleet` command runs the existing full audit engine across a
//! list of repositories and emits a consolidated matrix that the JMCP universe
//! dashboard consumes. It composes the audit engine (it does not reimplement any
//! scoring logic); each repo is scored with `run_audit_with_options` and the
//! relevant report fields are projected into a stable matrix row.

use crate::audit::{run_audit_with_options, AuditOptions};
use crate::model::{Finding, Report};
use anyhow::{bail, Context, Result};
use serde::Serialize;
use std::path::{Path, PathBuf};

/// Stable note emitted in place of a wall-clock timestamp so the matrix is
/// reproducible for dashboard diffing and golden tests.
const GENERATED_AT_NOTE: &str =
    "Generated by jankurai fleet; per-repo audits are deterministic and carry their own timestamps.";

/// Maximum number of findings projected into each matrix row.
const TOP_FINDINGS_LIMIT: usize = 5;

/// Maximum number of tool-adoption opportunities projected into each matrix row.
const TOP_TOOL_OPPORTUNITIES_LIMIT: usize = 5;

/// Arguments for the fleet command.
#[derive(Debug, Clone)]
pub struct FleetArgs {
    /// Repo paths supplied positionally. When empty, the fleet list is read
    /// from `~/.jankurai/fleet.toml` if present.
    pub repos: Vec<PathBuf>,
    /// Optional output file; when absent the matrix is written to stdout.
    pub out: Option<String>,
    /// Output format: `json` (default) or `md`.
    pub format: String,
    /// When set, exit nonzero if any repo scores below this threshold.
    pub fail_under: Option<i32>,
}

/// One row of the consolidated fleet matrix, one per audited repo.
#[derive(Debug, Clone, Serialize)]
pub struct FleetRow {
    pub name: String,
    pub path: String,
    pub score: i32,
    pub raw: i32,
    pub caps: Vec<String>,
    pub hard_findings: usize,
    pub hl_level: String,
    pub top_findings: Vec<String>,
    pub top_tool_opportunities: Vec<String>,
}

/// Aggregate totals across the fleet, mirroring the census summary style used
/// by the public-repo-scores aggregation.
#[derive(Debug, Clone, Serialize)]
pub struct FleetTotals {
    pub repo_count: usize,
    pub audited: usize,
    pub failed: usize,
    pub min_score: Option<i32>,
    pub max_score: Option<i32>,
    pub average_score: Option<f64>,
    pub total_hard_findings: usize,
    pub below_threshold: usize,
}

/// A repo that could not be audited, recorded so callers see partial failures.
#[derive(Debug, Clone, Serialize)]
pub struct FleetError {
    pub path: String,
    pub error: String,
}

/// The full consolidated matrix: the data contract consumed by the dashboard.
#[derive(Debug, Clone, Serialize)]
pub struct FleetMatrix {
    pub generated_at_note: String,
    pub repos: Vec<FleetRow>,
    pub totals: FleetTotals,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub errors: Vec<FleetError>,
}

/// Entry point for `jankurai fleet`.
pub fn run(args: FleetArgs) -> Result<()> {
    let repos = resolve_repos(&args.repos)?;
    if repos.is_empty() {
        bail!("no repos to audit; pass repo paths or populate ~/.jankurai/fleet.toml");
    }

    let mut rows = Vec::new();
    let mut errors = Vec::new();
    for repo in &repos {
        if !repo.exists() {
            // A missing path is a fatal configuration error: surface it directly.
            bail!("repo path does not exist: {}", repo.display());
        }
        match audit_repo(repo) {
            Ok(report) => rows.push(build_row(repo, &report)),
            Err(err) => errors.push(FleetError {
                path: display_path(repo),
                error: err.to_string(),
            }),
        }
    }

    let matrix = build_matrix(rows, errors, args.fail_under);
    let rendered = match args.format.as_str() {
        "md" => render_markdown(&matrix),
        "json" => serde_json::to_string_pretty(&matrix)?,
        other => bail!("unknown format '{other}'; expected 'json' or 'md'"),
    };

    emit(&args.out, &rendered)?;

    if let Some(threshold) = args.fail_under {
        if matrix.totals.below_threshold > 0 {
            bail!(
                "{} repo(s) scored below the fail-under threshold of {}",
                matrix.totals.below_threshold,
                threshold
            );
        }
    }

    Ok(())
}

/// Resolve the fleet list: explicit positional repos take precedence, otherwise
/// fall back to `~/.jankurai/fleet.toml` when present.
fn resolve_repos(explicit: &[PathBuf]) -> Result<Vec<PathBuf>> {
    if !explicit.is_empty() {
        return Ok(explicit.to_vec());
    }
    match fleet_config_path() {
        Some(path) if path.exists() => read_fleet_config(&path),
        _ => Ok(Vec::new()),
    }
}

fn fleet_config_path() -> Option<PathBuf> {
    std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".jankurai/fleet.toml"))
}

/// Read the `repos` array from `~/.jankurai/fleet.toml`.
fn read_fleet_config(path: &Path) -> Result<Vec<PathBuf>> {
    let text = std::fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    parse_fleet_config(&text)
}

/// Parse a fleet config body. Expected shape: `repos = ["/a", "/b"]`.
fn parse_fleet_config(text: &str) -> Result<Vec<PathBuf>> {
    let value: toml::Value = toml::from_str(text).with_context(|| "parse fleet config as TOML")?;
    let repos = value
        .get("repos")
        .and_then(|v| v.as_array())
        .map(|items| {
            items
                .iter()
                .filter_map(|item| item.as_str())
                .map(PathBuf::from)
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    Ok(repos)
}

/// Run the existing full audit engine over a single repo.
fn audit_repo(repo: &Path) -> Result<Report> {
    run_audit_with_options(repo, &[], AuditOptions::default())
        .with_context(|| format!("audit {}", repo.display()))
}

/// Project a `Report` into a matrix row. All scoring lives in the audit engine;
/// this only selects and shapes existing report fields.
fn build_row(repo: &Path, report: &Report) -> FleetRow {
    let hard_findings = report
        .decision
        .as_ref()
        .map(|d| d.hard_findings)
        .unwrap_or_else(|| {
            report
                .findings
                .iter()
                .filter(|f| f.hardness == "hard")
                .count()
        });

    FleetRow {
        name: repo_name(repo),
        path: display_path(repo),
        score: report.score,
        raw: report.raw_score,
        caps: report.caps_applied.clone(),
        hard_findings,
        hl_level: report.observed_conformance_level.clone(),
        top_findings: top_findings(&report.findings),
        top_tool_opportunities: top_tool_opportunities(report),
    }
}

/// Sort findings hard-first then by severity rank, returning short summaries.
fn top_findings(findings: &[Finding]) -> Vec<String> {
    let mut sorted: Vec<&Finding> = findings.iter().collect();
    sorted.sort_by(|a, b| {
        let a_hard = u8::from(a.hardness != "hard");
        let b_hard = u8::from(b.hardness != "hard");
        a_hard
            .cmp(&b_hard)
            .then_with(|| severity_rank(&a.severity).cmp(&severity_rank(&b.severity)))
            .then_with(|| a.check_id.cmp(&b.check_id))
    });
    sorted
        .into_iter()
        .take(TOP_FINDINGS_LIMIT)
        .map(|f| format!("{} {} {}: {}", f.severity, f.category, f.path, f.problem))
        .collect()
}

/// Lower rank sorts first (more severe first).
fn severity_rank(value: &str) -> i32 {
    match value {
        "critical" => 0,
        "high" => 1,
        "error" => 1,
        "medium" => 2,
        "low" => 3,
        _ => 2,
    }
}

/// Tool-adoption opportunities are applicable tools that have not yet reached
/// CI-backed evidence (status `missing` or `configured`).
fn top_tool_opportunities(report: &Report) -> Vec<String> {
    report
        .tool_adoption
        .items
        .iter()
        .filter(|item| item.applicable && matches!(item.status.as_str(), "missing" | "configured"))
        .take(TOP_TOOL_OPPORTUNITIES_LIMIT)
        .map(|item| format!("{} ({})", item.id, item.status))
        .collect()
}

/// Build the matrix with aggregate totals from the projected rows.
fn build_matrix(
    rows: Vec<FleetRow>,
    errors: Vec<FleetError>,
    fail_under: Option<i32>,
) -> FleetMatrix {
    let totals = aggregate_totals(&rows, &errors, fail_under);
    FleetMatrix {
        generated_at_note: GENERATED_AT_NOTE.to_string(),
        repos: rows,
        totals,
        errors,
    }
}

/// Compute min/max/average score, hard-finding totals, and below-threshold count.
fn aggregate_totals(
    rows: &[FleetRow],
    errors: &[FleetError],
    fail_under: Option<i32>,
) -> FleetTotals {
    let audited = rows.len();
    let min_score = rows.iter().map(|r| r.score).min();
    let max_score = rows.iter().map(|r| r.score).max();
    let average_score = if audited == 0 {
        None
    } else {
        let sum: i64 = rows.iter().map(|r| i64::from(r.score)).sum();
        Some(sum as f64 / audited as f64)
    };
    let total_hard_findings = rows.iter().map(|r| r.hard_findings).sum();
    let below_threshold = match fail_under {
        Some(threshold) => rows.iter().filter(|r| r.score < threshold).count(),
        None => 0,
    };
    FleetTotals {
        repo_count: audited + errors.len(),
        audited,
        failed: errors.len(),
        min_score,
        max_score,
        average_score,
        total_hard_findings,
        below_threshold,
    }
}

/// Render the matrix as a sentence-case Markdown table.
fn render_markdown(matrix: &FleetMatrix) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    let _ = writeln!(out, "# jankurai fleet matrix");
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", matrix.generated_at_note);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| Name | Path | Score | Raw | Caps | Hard | Conformance level | Top findings |"
    );
    let _ = writeln!(out, "| --- | --- | ---: | ---: | ---: | ---: | --- | --- |");
    for row in &matrix.repos {
        let findings = if row.top_findings.is_empty() {
            "none".to_string()
        } else {
            row.top_findings
                .iter()
                .map(|f| f.replace('|', "\\|"))
                .collect::<Vec<_>>()
                .join("; ")
        };
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} | {} | {} | {} |",
            row.name,
            row.path,
            row.score,
            row.raw,
            row.caps.len(),
            row.hard_findings,
            row.hl_level,
            findings
        );
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "## Totals");
    let _ = writeln!(out);
    let _ = writeln!(out, "- Repos: {}", matrix.totals.repo_count);
    let _ = writeln!(out, "- Audited: {}", matrix.totals.audited);
    let _ = writeln!(out, "- Failed: {}", matrix.totals.failed);
    let _ = writeln!(
        out,
        "- Score range: {} to {}",
        matrix
            .totals
            .min_score
            .map(|s| s.to_string())
            .unwrap_or_else(|| "n/a".into()),
        matrix
            .totals
            .max_score
            .map(|s| s.to_string())
            .unwrap_or_else(|| "n/a".into())
    );
    if let Some(avg) = matrix.totals.average_score {
        let _ = writeln!(out, "- Average score: {avg:.1}");
    }
    let _ = writeln!(
        out,
        "- Hard findings: {}",
        matrix.totals.total_hard_findings
    );
    let _ = writeln!(out, "- Below threshold: {}", matrix.totals.below_threshold);
    if !matrix.errors.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "## Errors");
        let _ = writeln!(out);
        for err in &matrix.errors {
            let _ = writeln!(out, "- {}: {}", err.path, err.error);
        }
    }
    out
}

/// Write the rendered matrix to the chosen sink (stdout or a file).
fn emit(out: &Option<String>, rendered: &str) -> Result<()> {
    match out {
        Some(path) => crate::render::write_json(path, rendered),
        None => {
            println!("{rendered}");
            Ok(())
        }
    }
}

fn repo_name(repo: &Path) -> String {
    repo.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .filter(|n| !n.is_empty())
        .unwrap_or_else(|| display_path(repo))
}

fn display_path(repo: &Path) -> String {
    repo.to_string_lossy().into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn finding(severity: &str, hardness: &str, check_id: &str, problem: &str) -> Finding {
        Finding {
            severity: severity.to_string(),
            category: "test".to_string(),
            path: "src/lib.rs".to_string(),
            problem: problem.to_string(),
            agent_fix: String::new(),
            evidence: vec![],
            check_id: check_id.to_string(),
            hardness: hardness.to_string(),
            confidence: 1.0,
            evidence_kind: "static".to_string(),
            rerun_command: String::new(),
            fingerprint: check_id.to_string(),
            rule_id: None,
            tlr: None,
            lane: None,
            docs_url: None,
            owner: None,
            line: None,
            matched_term: None,
            reason: None,
        }
    }

    fn mock_row(name: &str, score: i32, hard: usize) -> FleetRow {
        FleetRow {
            name: name.to_string(),
            path: format!("/repos/{name}"),
            score,
            raw: score + 2,
            caps: vec!["EXAMPLE-CAP".to_string()],
            hard_findings: hard,
            hl_level: "HL3".to_string(),
            top_findings: vec!["high test src/lib.rs: example".to_string()],
            top_tool_opportunities: vec!["clippy (missing)".to_string()],
        }
    }

    #[test]
    fn matrix_json_shape_is_stable() {
        let rows = vec![mock_row("alpha", 92, 0), mock_row("beta", 88, 2)];
        let matrix = build_matrix(rows, Vec::new(), Some(85));
        let json = serde_json::to_value(&matrix).unwrap();

        assert_eq!(
            json["generated_at_note"], GENERATED_AT_NOTE,
            "note must be deterministic, not a wall-clock timestamp"
        );
        let repos = json["repos"].as_array().unwrap();
        assert_eq!(repos.len(), 2);
        let first = &repos[0];
        for key in [
            "name",
            "path",
            "score",
            "raw",
            "caps",
            "hard_findings",
            "hl_level",
            "top_findings",
            "top_tool_opportunities",
        ] {
            assert!(first.get(key).is_some(), "row missing key {key}");
        }
        let totals = &json["totals"];
        assert_eq!(totals["repo_count"], 2);
        assert_eq!(totals["audited"], 2);
        assert_eq!(totals["min_score"], 88);
        assert_eq!(totals["max_score"], 92);
        assert_eq!(totals["total_hard_findings"], 2);
        assert_eq!(totals["below_threshold"], 0);
    }

    #[test]
    fn fail_under_counts_repos_below_threshold() {
        let rows = vec![mock_row("alpha", 92, 0), mock_row("beta", 70, 1)];
        let matrix = build_matrix(rows, Vec::new(), Some(85));
        assert_eq!(matrix.totals.below_threshold, 1);
    }

    #[test]
    fn no_fail_under_leaves_below_threshold_zero() {
        let rows = vec![mock_row("alpha", 50, 0)];
        let matrix = build_matrix(rows, Vec::new(), None);
        assert_eq!(matrix.totals.below_threshold, 0);
    }

    #[test]
    fn top_findings_orders_hard_then_severity() {
        let findings = vec![
            finding("low", "soft", "soft-low", "soft low"),
            finding("high", "hard", "hard-high", "hard high"),
            finding("critical", "soft", "soft-critical", "soft critical"),
        ];
        let top = top_findings(&findings);
        assert_eq!(top.len(), 3);
        assert!(top[0].contains("hard high"), "hard finding must sort first");
        assert!(top[1].contains("soft critical"));
        assert!(top[2].contains("soft low"));
    }

    #[test]
    fn top_findings_limited_to_five() {
        let findings: Vec<Finding> = (0..10)
            .map(|i| finding("high", "soft", &format!("check-{i:02}"), "p"))
            .collect();
        let top = top_findings(&findings);
        assert_eq!(top.len(), TOP_FINDINGS_LIMIT);
    }

    #[test]
    fn fleet_config_parses_repos_array() {
        let repos = parse_fleet_config("repos = [\"/a/one\", \"/b/two\"]").unwrap();
        assert_eq!(
            repos,
            vec![PathBuf::from("/a/one"), PathBuf::from("/b/two")]
        );
    }

    #[test]
    fn fleet_config_missing_repos_is_empty() {
        let repos = parse_fleet_config("other = 1").unwrap();
        assert!(repos.is_empty());
    }

    #[test]
    fn markdown_render_uses_sentence_case_headings() {
        let matrix = build_matrix(vec![mock_row("alpha", 92, 0)], Vec::new(), None);
        let md = render_markdown(&matrix);
        assert!(md.contains("# jankurai fleet matrix"));
        assert!(md.contains("| Name | Path | Score |"));
        assert!(md.contains("alpha"));
        // No screaming all-caps section markers in user-visible output.
        assert!(!md.contains("FLEET MATRIX"));
    }
}
